package flightproject.AdminP;

import flightproject.DBConnection;
import flightproject.FlightAgentP.FlightAgentModel;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class AdminUI extends javax.swing.JFrame {
    private Connection MyconObj=flightproject.DBConnection.connectDB();
    private Statement MystaObj=null;
    private ResultSet MyresObj=null;
    private int requestsId, passengerId, flightAgentId;
    private String passengerFullName, passengerUsername, passengerPassword, passengerEmail, passengerPhoneNumber;
    private String flightAgentFullName, flightAgentUsername, flightAgentPassword, flightAgentEmail;
    java.util.Date passengerDateofBirth;
    public AdminUI() {
        initComponents();
        DBConnection.connectDB();
        updateFlightAgentsTable();
        FlightAgentsManagementPanel.setVisible(true);
        PassengerManagementPanel.setVisible(false);
        RequestsPanel.setVisible(false);
        FlightAgentsTabPanel.setBackground(new Color(104, 173, 211));
        PassengersTabPanel.setBackground(new Color(56, 146, 196));
        RequestsTabPanel.setBackground(new Color(56, 146, 196));
    }
    
    private void updateFlightAgentsTable(){
        try{
            MystaObj=MyconObj.createStatement();
            MyresObj=MystaObj.executeQuery("SELECT * FROM ROOT.FLIGHTAGENTS");
            Table_1.setModel(DbUtils.resultSetToTableModel(MyresObj));
       }
       catch(SQLException e){  
        }
    }
    
    private void updatePassengersTable(){
        try{
            MystaObj=MyconObj.createStatement();
            MyresObj=MystaObj.executeQuery("SELECT * FROM ROOT.PASSENGERS");
            PassengersTable.setModel(DbUtils.resultSetToTableModel(MyresObj));
       }
       catch(SQLException e){ 
        }
    }
    
    private void updateRequestsTable(){
        try{
            MystaObj=MyconObj.createStatement();
            MyresObj=MystaObj.executeQuery("SELECT * FROM ROOT.REQUESTS");
            RequestsTable.setModel(DbUtils.resultSetToTableModel(MyresObj));
       }
       catch(SQLException e){   
        } 
    }
    
    private void getPassengerFields(){
        passengerFullName = passengerFullNameTxt.getText().trim();
        passengerUsername = passengerUsernameTxt.getText().trim();
        passengerPassword = passengerPasswordTxt.getText();
        passengerEmail = passengerEmailTxt.getText().trim();
        passengerPhoneNumber = passengerPhoneNumberTxt.getText().trim();
        passengerDateofBirth = passengerDateofBirthChooser.getDate();
    }
    
    private void clearPassengerFields(){
        passengerIdTxt.setText("");
        passengerFullNameTxt.setText("");
        passengerUsernameTxt.setText("");
        passengerPasswordTxt.setText("");
        passengerPhoneNumberTxt.setText("");
        passengerEmailTxt.setText("");
    }
    
    private void getFlightAgentsFields(){
        flightAgentFullName = flightAgentFullnameTxt.getText().trim();
        flightAgentUsername = flightagentUsernameTxt.getText().trim();
        flightAgentPassword = flightAgentPasswordTxt.getText();
        flightAgentEmail = flightAgentEmailTxt.getText().trim();
    }
    
    private void clearFlightAgentsFields(){
        flightAgentIdTxt.setText("");
        flightAgentFullnameTxt.setText("");
        flightagentUsernameTxt.setText("");
        flightAgentPasswordTxt.setText("");
        flightAgentEmailTxt.setText("");
    }
    
    public boolean emptyFlightagentField(){
        if(flightAgentFullName.equals("") || flightAgentUsername.equals("") || flightAgentPassword.equals("") || flightAgentEmail.equals("")){
            return true;
        }
        return false;
    }
    
    public boolean emptyPassengerField(){
        if(passengerFullName.equals("") ||  passengerUsername.equals("") || passengerPassword.equals("") || passengerEmail.equals("") || passengerPhoneNumber.equals("")){
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        FlightAgentsTabPanel = new javax.swing.JPanel();
        FlightAgentManagemnetTabLabel = new javax.swing.JLabel();
        PassengersTabPanel = new javax.swing.JPanel();
        PassengersManagementTabLabel = new javax.swing.JLabel();
        RequestsTabPanel = new javax.swing.JPanel();
        RequestsTabLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        RequestsPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RequestsTable = new javax.swing.JTable();
        topPanel = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        RequestsIdTxt = new javax.swing.JTextField();
        RequestDeleteButton = new javax.swing.JButton();
        RequestsHeaderLabel = new javax.swing.JLabel();
        PassengerManagementPanel = new javax.swing.JPanel();
        PassengerIdLabel = new javax.swing.JLabel();
        PassengerFullnameLabel = new javax.swing.JLabel();
        PassengerUsernameLabel = new javax.swing.JLabel();
        PassengerDateofBirthLabel = new javax.swing.JLabel();
        PassengerPasswordLabel = new javax.swing.JLabel();
        PassengerPhonenumberLabel = new javax.swing.JLabel();
        PassengerEmailLabel = new javax.swing.JLabel();
        passengerIdTxt = new javax.swing.JTextField();
        passengerFullNameTxt = new javax.swing.JTextField();
        passengerUsernameTxt = new javax.swing.JTextField();
        passengerPasswordTxt = new javax.swing.JTextField();
        passengerPhoneNumberTxt = new javax.swing.JTextField();
        passengerEmailTxt = new javax.swing.JTextField();
        passengerDateofBirthChooser = new com.toedter.calendar.JDateChooser();
        PassengerUpdateButton = new javax.swing.JButton();
        PassengerAddButton = new javax.swing.JButton();
        PassengerDeleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PassengersTable = new javax.swing.JTable();
        PassengerHeaderLabel = new javax.swing.JLabel();
        FlightAgentsManagementPanel = new javax.swing.JPanel();
        flightAgentPasswordTxt = new javax.swing.JTextField();
        FlightagentAddButton = new javax.swing.JButton();
        flightAgentFullnameTxt = new javax.swing.JTextField();
        FlightagentDeleteButton = new javax.swing.JButton();
        flightagentUsernameTxt = new javax.swing.JTextField();
        FlightagentUpdateButton = new javax.swing.JButton();
        flightAgentIdTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        FlightAgentHeaderLabel = new javax.swing.JLabel();
        flightAgentEmailTxt = new javax.swing.JTextField();
        FlightagentIdLabel = new javax.swing.JLabel();
        FlightagentFullnameLabel = new javax.swing.JLabel();
        FlightagentUsernameLabel = new javax.swing.JLabel();
        FlightagentPasswordLabel = new javax.swing.JLabel();
        FlightAgentEmailLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(231, 231, 231));

        SidePanel.setBackground(new java.awt.Color(56, 146, 196));
        SidePanel.setForeground(new java.awt.Color(255, 255, 255));

        FlightAgentsTabPanel.setBackground(new java.awt.Color(56, 146, 196));
        FlightAgentsTabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightAgentsTabPanelMouseClicked(evt);
            }
        });

        FlightAgentManagemnetTabLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FlightAgentManagemnetTabLabel.setText("Flight Agents");

        javax.swing.GroupLayout FlightAgentsTabPanelLayout = new javax.swing.GroupLayout(FlightAgentsTabPanel);
        FlightAgentsTabPanel.setLayout(FlightAgentsTabPanelLayout);
        FlightAgentsTabPanelLayout.setHorizontalGroup(
            FlightAgentsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightAgentsTabPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(FlightAgentManagemnetTabLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        FlightAgentsTabPanelLayout.setVerticalGroup(
            FlightAgentsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlightAgentsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FlightAgentManagemnetTabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PassengersTabPanel.setBackground(new java.awt.Color(56, 146, 196));
        PassengersTabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengersTabPanelMouseClicked(evt);
            }
        });

        PassengersManagementTabLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PassengersManagementTabLabel.setText("Passengers");

        javax.swing.GroupLayout PassengersTabPanelLayout = new javax.swing.GroupLayout(PassengersTabPanel);
        PassengersTabPanel.setLayout(PassengersTabPanelLayout);
        PassengersTabPanelLayout.setHorizontalGroup(
            PassengersTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengersTabPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(PassengersManagementTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PassengersTabPanelLayout.setVerticalGroup(
            PassengersTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengersTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PassengersManagementTabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        RequestsTabPanel.setBackground(new java.awt.Color(56, 146, 196));
        RequestsTabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RequestsTabPanelMouseClicked(evt);
            }
        });

        RequestsTabLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RequestsTabLabel.setText("Requests");

        javax.swing.GroupLayout RequestsTabPanelLayout = new javax.swing.GroupLayout(RequestsTabPanel);
        RequestsTabPanel.setLayout(RequestsTabPanelLayout);
        RequestsTabPanelLayout.setHorizontalGroup(
            RequestsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestsTabPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(RequestsTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RequestsTabPanelLayout.setVerticalGroup(
            RequestsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RequestsTabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FlightAgentsTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PassengersTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RequestsTabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(FlightAgentsTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PassengersTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RequestsTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        RequestsPanel.setBackground(new java.awt.Color(231, 231, 231));

        tablePanel.setBackground(new java.awt.Color(231, 231, 231));

        RequestsTable.setBackground(new java.awt.Color(231, 231, 231));
        RequestsTable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RequestsTable.setForeground(new java.awt.Color(51, 51, 51));
        RequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(RequestsTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        topPanel.setBackground(new java.awt.Color(231, 231, 231));

        IdLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(51, 51, 51));
        IdLabel.setText("ID       :");

        RequestsIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        RequestsIdTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RequestsIdTxt.setForeground(new java.awt.Color(51, 51, 51));

        RequestDeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        RequestDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RequestDeleteButton.setForeground(new java.awt.Color(231, 231, 231));
        RequestDeleteButton.setText("Delete");
        RequestDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestDeleteButtonActionPerformed(evt);
            }
        });

        RequestsHeaderLabel.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        RequestsHeaderLabel.setForeground(new java.awt.Color(51, 51, 51));
        RequestsHeaderLabel.setText("Account Restoration Requests");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(RequestsHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(RequestsIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(RequestDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RequestsHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestsIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout RequestsPanelLayout = new javax.swing.GroupLayout(RequestsPanel);
        RequestsPanel.setLayout(RequestsPanelLayout);
        RequestsPanelLayout.setHorizontalGroup(
            RequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RequestsPanelLayout.setVerticalGroup(
            RequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestsPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PassengerManagementPanel.setBackground(new java.awt.Color(231, 231, 231));

        PassengerIdLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerIdLabel.setText("ID                   :");

        PassengerFullnameLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerFullnameLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerFullnameLabel.setText("Full Name      :");

        PassengerUsernameLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerUsernameLabel.setText("Username    :");

        PassengerDateofBirthLabel.setBackground(new java.awt.Color(255, 255, 255));
        PassengerDateofBirthLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerDateofBirthLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerDateofBirthLabel.setText("Date of Birth    :");

        PassengerPasswordLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerPasswordLabel.setText("Password     :");

        PassengerPhonenumberLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerPhonenumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerPhonenumberLabel.setText("Phone Number  :");

        PassengerEmailLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        PassengerEmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerEmailLabel.setText("E-Mail                 :");

        passengerIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerIdTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerIdTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerFullNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerFullNameTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerFullNameTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerUsernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerUsernameTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerUsernameTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerPasswordTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerPasswordTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerPasswordTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerPhoneNumberTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerPhoneNumberTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerPhoneNumberTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        passengerEmailTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passengerEmailTxt.setForeground(new java.awt.Color(0, 0, 0));

        passengerDateofBirthChooser.setBackground(new java.awt.Color(255, 255, 255));
        passengerDateofBirthChooser.setForeground(new java.awt.Color(51, 51, 51));

        PassengerUpdateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PassengerUpdateButton.setText("Update");
        PassengerUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerUpdateButtonActionPerformed(evt);
            }
        });

        PassengerAddButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PassengerAddButton.setText("Add");
        PassengerAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerAddButtonActionPerformed(evt);
            }
        });

        PassengerDeleteButton.setBackground(new java.awt.Color(185, 0, 0));
        PassengerDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PassengerDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        PassengerDeleteButton.setText("Delete");
        PassengerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerDeleteButtonActionPerformed(evt);
            }
        });

        PassengersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(PassengersTable);

        PassengerHeaderLabel.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        PassengerHeaderLabel.setForeground(new java.awt.Color(51, 51, 51));
        PassengerHeaderLabel.setText("Passengers Management");

        javax.swing.GroupLayout PassengerManagementPanelLayout = new javax.swing.GroupLayout(PassengerManagementPanel);
        PassengerManagementPanel.setLayout(PassengerManagementPanelLayout);
        PassengerManagementPanelLayout.setHorizontalGroup(
            PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PassengerManagementPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PassengerAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PassengerUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(PassengerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(PassengerManagementPanelLayout.createSequentialGroup()
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PassengerManagementPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(PassengerHeaderLabel))
                    .addGroup(PassengerManagementPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passengerFullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PassengerManagementPanelLayout.createSequentialGroup()
                                    .addComponent(PassengerIdLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passengerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PassengerManagementPanelLayout.createSequentialGroup()
                                    .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PassengerPasswordLabel)
                                            .addComponent(PassengerUsernameLabel))
                                        .addGroup(PassengerManagementPanelLayout.createSequentialGroup()
                                            .addComponent(PassengerFullnameLabel)
                                            .addGap(2, 2, 2)))
                                    .addGap(22, 22, 22)
                                    .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passengerUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passengerPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(62, 62, 62)
                        .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PassengerDateofBirthLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PassengerEmailLabel))
                            .addComponent(PassengerPhonenumberLabel))
                        .addGap(25, 25, 25)
                        .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passengerDateofBirthChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passengerPhoneNumberTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passengerEmailTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        PassengerManagementPanelLayout.setVerticalGroup(
            PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerManagementPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PassengerHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passengerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PassengerIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PassengerDateofBirthLabel)
                    .addComponent(passengerDateofBirthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerFullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerFullnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerPhoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerPhonenumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PassengerManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FlightAgentsManagementPanel.setBackground(new java.awt.Color(231, 231, 231));

        flightAgentPasswordTxt.setBackground(new java.awt.Color(255, 255, 255));
        flightAgentPasswordTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flightAgentPasswordTxt.setForeground(new java.awt.Color(51, 51, 51));

        FlightagentAddButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FlightagentAddButton.setText("Add");
        FlightagentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightagentAddButtonActionPerformed(evt);
            }
        });

        flightAgentFullnameTxt.setBackground(new java.awt.Color(255, 255, 255));
        flightAgentFullnameTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flightAgentFullnameTxt.setForeground(new java.awt.Color(51, 51, 51));

        FlightagentDeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        FlightagentDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FlightagentDeleteButton.setForeground(new java.awt.Color(231, 231, 231));
        FlightagentDeleteButton.setText("Delete");
        FlightagentDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightagentDeleteButtonActionPerformed(evt);
            }
        });

        flightagentUsernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        flightagentUsernameTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flightagentUsernameTxt.setForeground(new java.awt.Color(51, 51, 51));

        FlightagentUpdateButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FlightagentUpdateButton.setText("Update");
        FlightagentUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightagentUpdateButtonActionPerformed(evt);
            }
        });

        flightAgentIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        flightAgentIdTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flightAgentIdTxt.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(231, 231, 231));

        FlightAgentHeaderLabel.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        FlightAgentHeaderLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightAgentHeaderLabel.setText("Flight Agents Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(FlightAgentHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(FlightAgentHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        flightAgentEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        flightAgentEmailTxt.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flightAgentEmailTxt.setForeground(new java.awt.Color(51, 51, 51));

        FlightagentIdLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FlightagentIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightagentIdLabel.setText("ID                     :");

        FlightagentFullnameLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FlightagentFullnameLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightagentFullnameLabel.setText("Full Name    :");

        FlightagentUsernameLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FlightagentUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightagentUsernameLabel.setText("Username    :");

        FlightagentPasswordLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FlightagentPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightagentPasswordLabel.setText("Password    :");

        FlightAgentEmailLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FlightAgentEmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        FlightAgentEmailLabel.setText("E-mail             :");

        Table_1.setBackground(new java.awt.Color(204, 204, 204));
        Table_1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "full name", "user name", "password", "email"
            }
        ));
        jScrollPane1.setViewportView(Table_1);
        if (Table_1.getColumnModel().getColumnCount() > 0) {
            Table_1.getColumnModel().getColumn(3).setResizable(false);
            Table_1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout FlightAgentsManagementPanelLayout = new javax.swing.GroupLayout(FlightAgentsManagementPanel);
        FlightAgentsManagementPanel.setLayout(FlightAgentsManagementPanelLayout);
        FlightAgentsManagementPanelLayout.setHorizontalGroup(
            FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                        .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FlightagentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FlightagentFullnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FlightagentUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flightAgentFullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightagentUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightAgentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                                        .addComponent(FlightAgentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(flightAgentEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                                        .addComponent(FlightagentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(flightAgentPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(FlightagentAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(FlightagentUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(FlightagentDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlightAgentsManagementPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        FlightAgentsManagementPanelLayout.setVerticalGroup(
            FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightAgentsManagementPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightagentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightAgentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightagentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightAgentPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightAgentFullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightAgentEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightAgentEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightagentFullnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightagentUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightagentUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(FlightAgentsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightagentUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightagentDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightagentAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FlightAgentsManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PassengerManagementPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RequestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(FlightAgentsManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addComponent(PassengerManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addComponent(RequestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void FlightagentAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightagentAddButtonActionPerformed
        flightAgentId =FlightAgentModel.generateID();
        getFlightAgentsFields();
        if(emptyFlightagentField()){
            JOptionPane.showMessageDialog(null, "Complete Missing Data Fields!");
        }else{
            try{
                java.sql.PreparedStatement add = MyconObj.prepareStatement("Insert Into ROOT.FLIGHTAGENTS values (?,?,?,?,?)");
                add.setInt(1, flightAgentId);
                add.setString(2, flightAgentFullName);
                add.setString(3, flightAgentEmail);
                add.setString(4, flightAgentUsername);
                add.setString(5, flightAgentPassword);
                int row=add.executeUpdate();
                clearFlightAgentsFields();
            }
            catch(SQLException e){
            }
        }
        updateFlightAgentsTable();
    }//GEN-LAST:event_FlightagentAddButtonActionPerformed

    private void FlightagentDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightagentDeleteButtonActionPerformed
        try{
            String sql="Delete FROM ROOT.FLIGHTAGENTS where id ="+flightAgentIdTxt.getText();
            Statement add=MyconObj.createStatement();
            add.executeUpdate(sql);
            clearFlightAgentsFields();
        }
        catch(SQLException e){
        }
        updateFlightAgentsTable();
    }//GEN-LAST:event_FlightagentDeleteButtonActionPerformed

    private void FlightagentUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightagentUpdateButtonActionPerformed
        getFlightAgentsFields();
        if(emptyFlightagentField() || flightAgentIdTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Missing Data Fields!");
        }else{
            try{
                flightAgentId = Integer.parseInt(flightAgentIdTxt.getText());
                String sql="Update ROOT.FLIGHTAGENTS Set full_name = ?, username = ?, password = ? , email = ? where ID = ?";
                java.sql.PreparedStatement mystatObj=  MyconObj.prepareStatement(sql);
                mystatObj.setString(1, flightAgentFullName);
                mystatObj.setString(2, flightAgentUsername);
                mystatObj.setString(3, flightAgentPassword);
                mystatObj.setString(4, flightAgentEmail);
                mystatObj.setInt(5, flightAgentId);
                mystatObj.executeUpdate();
                clearFlightAgentsFields();
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
        updateFlightAgentsTable();
    }//GEN-LAST:event_FlightagentUpdateButtonActionPerformed

    private void FlightAgentsTabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightAgentsTabPanelMouseClicked
        FlightAgentsManagementPanel.setVisible(true);
        PassengerManagementPanel.setVisible(false);
        RequestsPanel.setVisible(false);
        FlightAgentsTabPanel.setBackground(new Color(104, 173, 211));
        PassengersTabPanel.setBackground(new Color(56, 146, 196));
        RequestsTabPanel.setBackground(new Color(56, 146, 196));
        updateFlightAgentsTable();
    }//GEN-LAST:event_FlightAgentsTabPanelMouseClicked

    private void PassengersTabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengersTabPanelMouseClicked
        FlightAgentsManagementPanel.setVisible(false);
        PassengerManagementPanel.setVisible(true);
        RequestsPanel.setVisible(false);
        PassengersTabPanel.setBackground(new Color(104, 173, 211));
        FlightAgentsTabPanel.setBackground(new Color(56, 146, 196));
        RequestsTabPanel.setBackground(new Color(56, 146, 196));
        updatePassengersTable();
    }//GEN-LAST:event_PassengersTabPanelMouseClicked

    private void RequestsTabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestsTabPanelMouseClicked
        FlightAgentsManagementPanel.setVisible(false);
        PassengerManagementPanel.setVisible(false);
        RequestsPanel.setVisible(true);
        RequestsTabPanel.setBackground(new Color(104, 173, 211));
        PassengersTabPanel.setBackground(new Color(56, 146, 196));
        FlightAgentsTabPanel.setBackground(new Color(56, 146, 196));
        updateRequestsTable();
    }//GEN-LAST:event_RequestsTabPanelMouseClicked

    private void PassengerUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerUpdateButtonActionPerformed
        getPassengerFields();
        if(emptyPassengerField() || passengerIdTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Missing Data Fields!");
        }else{
            java.sql.Date sqlDate = new java.sql.Date(passengerDateofBirth.getTime());
            try{
                passengerId = Integer.parseInt( passengerIdTxt.getText());
                String sql="UPDATE ROOT.PASSENGERS SET FULLNAME = ?, USERNAME = ?, PASSWORD = ? , DATEOFBIRTH = ? , PHONENUMBER = ? , EMAIL = ? WHERE ID = ?";
                java.sql.PreparedStatement mystatObj=  MyconObj.prepareStatement(sql);
                mystatObj.setString(1, passengerFullName);
                mystatObj.setString(2, passengerUsername);
                mystatObj.setString(3, passengerPassword);
                mystatObj.setDate(4, sqlDate);
                mystatObj.setString(5, passengerPhoneNumber);
                mystatObj.setString(6,passengerEmail);
                mystatObj.setInt(7, passengerId);
                mystatObj.executeUpdate();
            }
            catch(SQLException e){

                e.printStackTrace();
            }
            clearPassengerFields();
        }
        updatePassengersTable();
    }//GEN-LAST:event_PassengerUpdateButtonActionPerformed

    private void PassengerAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerAddButtonActionPerformed
        getPassengerFields();
        java.sql.Date sqlDate = new java.sql.Date(passengerDateofBirth.getTime());
        passengerId = flightproject.PassengerP.Passenger.generateID();
        if(emptyPassengerField()){
            JOptionPane.showMessageDialog(null, "Complete Missing Data Fields!");
        }else{
            flightproject.PassengerP.Passenger.createNewUser(passengerId, passengerFullName, passengerUsername, passengerPassword, sqlDate, passengerPhoneNumber, passengerEmail);
            clearPassengerFields();
        }
        updatePassengersTable();
    }//GEN-LAST:event_PassengerAddButtonActionPerformed

    private void PassengerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerDeleteButtonActionPerformed
        passengerId = Integer.parseInt(passengerIdTxt.getText());
        try{
            String sql="Delete FROM ROOT.PASSENGERS where id ="+String.valueOf(passengerId);
            Statement add=MyconObj.createStatement();
            add.executeUpdate(sql);
        } catch(SQLException e){
        }
        updatePassengersTable();
        clearPassengerFields();
    }//GEN-LAST:event_PassengerDeleteButtonActionPerformed

    private void RequestDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestDeleteButtonActionPerformed
        requestsId = Integer.parseInt(RequestsIdTxt.getText());
        try{
            String sql="Delete FROM ROOT.REQUESTS where id ="+String.valueOf(requestsId);
            Statement add = MyconObj.createStatement();
            add.executeUpdate(sql);
        } catch(SQLException e){
        }
        updateRequestsTable();
        RequestsIdTxt.setText("");
    }//GEN-LAST:event_RequestDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlightAgentEmailLabel;
    private javax.swing.JLabel FlightAgentHeaderLabel;
    private javax.swing.JLabel FlightAgentManagemnetTabLabel;
    private javax.swing.JPanel FlightAgentsManagementPanel;
    private javax.swing.JPanel FlightAgentsTabPanel;
    private javax.swing.JButton FlightagentAddButton;
    private javax.swing.JButton FlightagentDeleteButton;
    private javax.swing.JLabel FlightagentFullnameLabel;
    private javax.swing.JLabel FlightagentIdLabel;
    private javax.swing.JLabel FlightagentPasswordLabel;
    private javax.swing.JButton FlightagentUpdateButton;
    private javax.swing.JLabel FlightagentUsernameLabel;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton PassengerAddButton;
    private javax.swing.JLabel PassengerDateofBirthLabel;
    private javax.swing.JButton PassengerDeleteButton;
    private javax.swing.JLabel PassengerEmailLabel;
    private javax.swing.JLabel PassengerFullnameLabel;
    private javax.swing.JLabel PassengerHeaderLabel;
    private javax.swing.JLabel PassengerIdLabel;
    private javax.swing.JPanel PassengerManagementPanel;
    private javax.swing.JLabel PassengerPasswordLabel;
    private javax.swing.JLabel PassengerPhonenumberLabel;
    private javax.swing.JButton PassengerUpdateButton;
    private javax.swing.JLabel PassengerUsernameLabel;
    private javax.swing.JLabel PassengersManagementTabLabel;
    private javax.swing.JPanel PassengersTabPanel;
    private javax.swing.JTable PassengersTable;
    private javax.swing.JButton RequestDeleteButton;
    private javax.swing.JLabel RequestsHeaderLabel;
    private javax.swing.JTextField RequestsIdTxt;
    private javax.swing.JPanel RequestsPanel;
    private javax.swing.JLabel RequestsTabLabel;
    private javax.swing.JPanel RequestsTabPanel;
    private javax.swing.JTable RequestsTable;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTable Table_1;
    private javax.swing.JTextField flightAgentEmailTxt;
    private javax.swing.JTextField flightAgentFullnameTxt;
    private javax.swing.JTextField flightAgentIdTxt;
    private javax.swing.JTextField flightAgentPasswordTxt;
    private javax.swing.JTextField flightagentUsernameTxt;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser passengerDateofBirthChooser;
    private javax.swing.JTextField passengerEmailTxt;
    private javax.swing.JTextField passengerFullNameTxt;
    private javax.swing.JTextField passengerIdTxt;
    private javax.swing.JTextField passengerPasswordTxt;
    private javax.swing.JTextField passengerPhoneNumberTxt;
    private javax.swing.JTextField passengerUsernameTxt;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
