/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flightproject.admin;

import flightproject.FlightAgent.FlightAgentC;
import flightproject.FlightAgent.FlightAgentModel;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author moham
 */
public class AdminUI extends javax.swing.JFrame {
    /**
     * Creates new form AdminUI
     */
    DefaultTableModel tableModel;
    
    public AdminUI() {
        initComponents();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        flightagents = new javax.swing.JPanel();
        addNewFlightAgent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFlightAgent = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        saveAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Flight Agents");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        flightagents.setBackground(new java.awt.Color(204, 204, 255));

        addNewFlightAgent.setBackground(new java.awt.Color(153, 204, 255));
        addNewFlightAgent.setText("Add New +");
        addNewFlightAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFlightAgentActionPerformed(evt);
            }
        });

        listFlightAgent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "name", "username", "email", "password"
            }
        ));
        jScrollPane1.setViewportView(listFlightAgent);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        saveAdd.setText("Save Added Row");
        saveAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout flightagentsLayout = new javax.swing.GroupLayout(flightagents);
        flightagents.setLayout(flightagentsLayout);
        flightagentsLayout.setHorizontalGroup(
            flightagentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightagentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewFlightAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAdd)
                .addGap(3, 3, 3)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(flightagentsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        flightagentsLayout.setVerticalGroup(
            flightagentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightagentsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(flightagentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewFlightAgent)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(saveAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(flightagents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightagents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      ArrayList<FlightAgentModel> agents = null;
        
      agents = FlightAgentC.getFlightAgents();
         System.out.println(agents);
       tableModel = (DefaultTableModel) listFlightAgent.getModel();
        tableModel.setRowCount(0);
        for (FlightAgentModel flightagent : agents) {
            Object rowData[] = {flightagent.getId(), flightagent.getName(), flightagent.getUsername(),flightagent.getEmail(),flightagent.getPassword()};
            tableModel.addRow(rowData);
        }
        flightagents.setVisible(true);
        listFlightAgent.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addNewFlightAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFlightAgentActionPerformed
       Object rowData[] = {'t', ' ', ' ',' ',};
        tableModel.addRow(rowData);
        
    }//GEN-LAST:event_addNewFlightAgentActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       // if(listFlightAgent.getSelectedRow()!= -1) {
               // remove selected row from the model
                String  selectedData = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 0);
               tableModel.removeRow(listFlightAgent.getSelectedRow());
               System.out.println("dds"+selectedData+"dds");
             FlightAgentC.deleteFlightAgent(selectedData);
          //  }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
             String  selectedid = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 0);
             String  selectedFullname = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 1);
             String  selectedUsername = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 2);
             String  selectedPassword = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 4);
             String  selectedEmail = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 3);
             System.out.println(selectedid+selectedEmail+selectedFullname+selectedUsername);
              FlightAgentC.updateFlightAgent(selectedid,selectedFullname, selectedEmail, selectedUsername,selectedPassword);
             
  
    }//GEN-LAST:event_updateActionPerformed

    private void saveAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveAddMouseClicked

             String  selectedFullname = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 1);
             String  selectedUsername = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 2);
            String  selectedPassword = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 4);
             String  selectedEmail = (String) tableModel.getValueAt(listFlightAgent.getSelectedRow(), 3);
             System.out.println(selectedEmail+selectedFullname+selectedUsername);
              FlightAgentC.addNewFlightAgent(selectedFullname, selectedEmail, selectedUsername,selectedPassword);
              jLabel1MouseClicked(evt);
    }//GEN-LAST:event_saveAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewFlightAgent;
    private javax.swing.JButton delete;
    private javax.swing.JPanel flightagents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listFlightAgent;
    private javax.swing.JButton saveAdd;
    private javax.swing.JPanel tab1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
